dist: bionic
language: node_js
node_js: 12
install:
  - npm install
script:
  - diff README.md <(scripts/generateRecipeTable.sh)
  - make buildAll
  - make buildAllDev
cache:
  directories:
   - output
   - .spago
