dist: bionic
language: node_js
node_js: 12
branches:
  only:
  - master
install:
  - npm install
script:
  - diff README.md <(scripts/generateRecipeTable.sh)
  - make testAllCI
  - make testAllCommands
cache:
  directories:
   - output
   - .spago
