dist: bionic
language: node_js
node_js: 12
branches:
  only:
  - master
before_install:
  - npm i pnpm
install:
  - pnpm install
script:
  - make testAllCommands
  - diff README.md <(scripts/generateRecipeTable.sh)
  - make testAllCI
